### ISSUE TITLE
only matching images ..different images with same face are not recogizing 

### ISSUE THREAD

**Issue by ShraddhaGadesha** [kairosinc/Kairos-SDK-Android#2]
I am adding image in gallery by getting image from gallery using enroll api.
Now for recognition I am using recognition api.If I pick same image from gallery ,Its giving me result properly.But I pick other image of same person (That is face is same as image i have enrolled) ,its giving me no result found .please help.

**Comment by coleca** [comment]
I would suggest using the "threshold" parameter and lowering it a value below the default, which I think it set at 0.80.

**Comment by ShraddhaGadesha** [comment]
Are you telling I should pass threshold parameter with value 0.80 in recognize api??

**Comment by coleca** [comment]
No, a value lower, you can go as low as 0.01.

**Comment by ShraddhaGadesha** [comment]
I am not understanding what you are Telling .My Question is that if I have uploaded my one image using enroll api ,and I upload that same image for recognition it's giving me proper result.But if I upload another image of mine(that is enrolled image and sec image for recognition faces are same) ,Its giving me no result found.(I think if images faces are same than It should be given result with name)

**Comment by cheezcake** [comment]
Hello I would like to leave your newsletter very much so.

**Comment by coleca** [comment]
I suggest trying the requests manually from something like Curl or Postman outside of the Android app.  We have extensive documentation available at: https://www.kairos.com/docs/face-recognition/
